// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewCategory struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewChapter struct {
	Name       string `json:"name"`
	CourseID   string `json:"courseID"`
	CategoryID string `json:"categoryID"`
}

type NewCourse struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	CategoryID  string `json:"categoryID"`
}
